version: "3"

services:
  angular:
    build: ./frontend
    ports:
      - "4200:4200"
  
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
      
  express:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/turisticka_agencija

